import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router'
import { HeroesComponent } from './heroes/heroes.component'
import { DashboardComponent } from './dashboard/dashboard.component'
import { HeroDetailComponent } from './hero-detail/hero-detail.component'

//A route always contains a string URL path to the resource, and the component generated by that path.
const routes: Routes = [
{ path: 'heroes', component: HeroesComponent },
{ path: 'dashboard', component: DashboardComponent},
//The colon before ID indincates this is a variable field in the URL.
{ path: "detail/:id", component: HeroDetailComponent},
{ path: '', redirectTo: '/dashboard', pathMatch: 'full'} //Default route when none specified
//Redirect is distinct from component because it will physically repoint the browser URL to where it wants to go, instead of just interpreting.
]

@NgModule({
  exports: [
    RouterModule
  ],
  imports: [
    //Initilaize the router and get it listening for browser location changes.
    RouterModule.forRoot(routes)
  ]
})
export class AppRoutingModule { }
